---
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: ec2-54-152-15-242.compute-1.amazonaws.com
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
  - git
  - sonar
  - ssh
  - cobertura
  - jenkins-ca-agile-central-build-publisher
  - jira
  - job-import-plugin
  - plain-credentials
  - rally-plugin
  - stash-pullrequest-builder
  - stashNotifier
  - token-macro
  - workflow-step-api
  - view-job-filters
jenkins_url_prefix: ""
